apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:34:07Z"
  name: carts-canary
  resourceVersion: "931832"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: d416f8c4-0c52-11ea-8de6-42010a84027a
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
